### ISSUE TITLE
Support multiple twitter accounts by add settings field to change `tweets` dir name

### ISSUE THREAD

**Issue by yuiseki** [gr2m/twitter-together#162]
**What’s missing?**

Manage tweeting of multiple (more than one) twitter account.

**Why?**

This GitHub Actions seems can manage tweets only one specific twitter account.
In my use case, I want to update two twitter accounts because it is separated as English and Japanese.
Manage multiple twitter account is already possible to create multiple GitHub repositories, but that's a pain...

So I want to manage multiple twitter account in one GitHub repository!

My idea is below:

It is complex and waste to support multiple accounts settings in one `twitter-together.yml` file, I think.

If we can add optional settings fields that specify any directory,
We can manage multiple twitter accounts by just put multiple `twitter-together.yml` file, like:
- `twitter-together-ja.yml`
- `twitter-together-en.yml`

```
    ...
    steps:
      - name: checkout master
        uses: actions/checkout@v2
      - name: Tweet
        uses: gr2m/twitter-together@v1.x
        with:
          tweets-dir: tweets-ja
        env:
          ...
```

**Alternatives you tried**

I haven't tried anything yet.
